version: '3.8'

services:
  ignite-nodejs-chapter05-challenge-pg:
    container_name: challenge-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=db
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
  ignite-nodejs-chapter05-challenge-redis:
    container_name: challenge-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data